version: "3.5"

services:
  postgres:
    container_name: postgres
    image: postgres:15
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h db-postgresql -U rinha" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '1GB'
  api1:
    hostname: api1
    image: phaalonso/rinha_backend_spring
    environment:
      PORT: 8080
      DATABASE_URL: jdbc:postgresql://postgres:5432/rinha
      VIRTUAL_THREADS: true
      JAVA_OPTS: -XX:+UseZGC -XX:MaxRAMPercentage=75 --enable-preview
      REDIS_URL: redis
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.75GB'
  api2:
    hostname: api2
    image: phaalonso/rinha_backend_spring
    environment:
      PORT: 8080
      DATABASE_URL: jdbc:postgresql://postgres:5432/rinha
      VIRTUAL_THREADS: true
      JAVA_OPTS: -XX:+UseZGC -XX:MaxRAMPercentage=75 --enable-preview
      REDIS_URL: redis
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.75GB'
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    tmpfs:
      - /tmp/people-cache:rw,nodev,nosuid,size=500M
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.25GB'
  redis:
    hostname: redis
    image: redis:latest
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.25GB'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
networks:
  default:
    driver: bridge
    name: rinha
