POST http://localhost:9999/pessoas
Content-Type: application/json

{
  "nome": "joao",
  "apelido": "11111111111111111111111111111111111",
  "nascimento": "2020-07-12",
  "stack": ["Nodejs", "PHP", "C"]
}

###

GET http://localhost:9999/pessoas/45f18c18-3f27-46bf-b397-f82438e49049
Content-Type: application/json

###

GET http://127.0.0.1:8080/people?t=PHP
Content-Type: application/json

###

GET http://localhost:9999/contagem-pessoas
Content-Type: application/json
