POST http://localhost:9999/people
Content-Type: application/json

{
  "name": "joao",
  "nick": "{{$random.email}}",
  "birthDate": "2020-07-12",
  "stack": ["Nodejs", "PHP", "C"]
}

###

GET http://127.0.0.1:8080/people/e2256e7a-c298-49b2-83d3-0283c89108d3
Content-Type: application/json

###

GET http://127.0.0.1:8080/people?t=PHP
Content-Type: application/json

###

GET http://localhost:9999/contagem-pessoas
Content-Type: application/json
